# Generated by Django 4.1 on 2022-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_comment_post_favoriteforpost_favoriteforcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
