# Generated by Django 4.1.3 on 2022-12-09 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteforcomment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='favoriteforcomment',
            name='user',
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=10000)),
                ('comment_date', models.DateField(auto_now=True)),
                ('tweet_flag', models.BooleanField(default=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_comment',
            },
        ),
    ]
